-- Enable pgvector extension for vector embeddings
create extension if not exists vector with schema extensions;

-- Create ai_memories table for storing user memories with vector embeddings
create table if not exists public.ai_memories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  content text not null,
  embedding extensions.vector(1536), -- OpenAI text-embedding-3-large uses 1536 dimensions
  metadata jsonb default '{}'::jsonb,
  chat_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  -- Create index on user_id for fast user-specific queries
  constraint ai_memories_user_id_fkey foreign key (user_id) references public.users(id) on delete cascade
);

-- Create index on user_id for efficient filtering
create index if not exists ai_memories_user_id_idx on public.ai_memories(user_id);

-- Create index on created_at for chronological queries
create index if not exists ai_memories_created_at_idx on public.ai_memories(created_at desc);

-- Create HNSW index for fast vector similarity search
-- HNSW (Hierarchical Navigable Small World) is optimal for large-scale vector search
create index if not exists ai_memories_embedding_idx on public.ai_memories
  using hnsw (embedding extensions.vector_cosine_ops)
  with (m = 16, ef_construction = 64);

-- Create function to update updated_at timestamp
create or replace function public.update_ai_memories_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Create trigger to automatically update updated_at
create trigger update_ai_memories_updated_at_trigger
  before update on public.ai_memories
  for each row
  execute function public.update_ai_memories_updated_at();

-- Create function for semantic memory search
create or replace function public.match_ai_memories(
  query_embedding extensions.vector(1536),
  query_user_id uuid,
  match_threshold float default 0.7,
  match_count int default 5
)
returns table (
  id uuid,
  user_id uuid,
  content text,
  metadata jsonb,
  chat_id text,
  created_at timestamptz,
  updated_at timestamptz,
  similarity float
)
language sql stable
as $$
  select
    ai_memories.id,
    ai_memories.user_id,
    ai_memories.content,
    ai_memories.metadata,
    ai_memories.chat_id,
    ai_memories.created_at,
    ai_memories.updated_at,
    1 - (ai_memories.embedding <=> query_embedding) as similarity
  from public.ai_memories
  where ai_memories.user_id = query_user_id
    and 1 - (ai_memories.embedding <=> query_embedding) > match_threshold
  order by ai_memories.embedding <=> query_embedding asc
  limit least(match_count, 50);
$$;

-- Enable RLS (Row Level Security)
alter table public.ai_memories enable row level security;

-- Create policy: Users can only read their own memories
create policy "Users can read own memories"
  on public.ai_memories
  for select
  using (user_id = auth.uid());

-- Create policy: Users can only insert their own memories
create policy "Users can insert own memories"
  on public.ai_memories
  for insert
  with check (user_id = auth.uid());

-- Create policy: Users can only update their own memories
create policy "Users can update own memories"
  on public.ai_memories
  for update
  using (user_id = auth.uid());

-- Create policy: Users can only delete their own memories
create policy "Users can delete own memories"
  on public.ai_memories
  for delete
  using (user_id = auth.uid());

-- Grant permissions
grant usage on schema public to authenticated;
grant all on public.ai_memories to authenticated;
grant execute on function public.match_ai_memories to authenticated;
grant execute on function public.update_ai_memories_updated_at to authenticated;

-- Add helpful comments
comment on table public.ai_memories is 'Stores user memories with vector embeddings for semantic search and AI personalization';
comment on column public.ai_memories.embedding is 'Vector embedding (1536 dimensions) generated by OpenAI text-embedding-3-large model via OpenRouter';
comment on column public.ai_memories.metadata is 'Additional metadata in JSON format (e.g., importance score, tags, source)';
comment on function public.match_ai_memories is 'Performs semantic similarity search on user memories using cosine distance';
